# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoAssistant
                                 A QGIS plugin
 AI-powered geospatial analysis assistant for QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-22
        git sha              : $Format:%H$
        copyright            : (C) 2025 by cug_cj
        email                : 3118345614@qq.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from .agent import Agent
from .tools import (list_project_layers, create_buffer, vector_overlay, fix_geometries,
                    resample_raster, get_raster_info, highlight_features)
from qgis.core import QgsProject
from qgis.PyQt import QtCore
import re
from PyQt5.QtCore import QThread, pyqtSignal, QCoreApplication
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QAction, QDialogButtonBox

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon

import logging
import os
import datetime

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .GeoAssistant_dialog import GeoAssistantDialog
import os.path


class GeoAssistant:
    """QGIS插件主类"""

    def __init__(self, iface):
        """初始化插件"""
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """

        # 将插件目录下的libs子目录添加到Python模块搜索路径的开头，以便在插件运行时可以导入该目录中的第三方库
        import sys, os
        plugin_dir = os.path.dirname(__file__)            # 局部变量（只在__init__方法内有效）
        libs_path = os.path.join(plugin_dir, 'libs')
        if libs_path not in sys.path:
            sys.path.insert(0, libs_path)

        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)      # 实例属性（整个类生命周期有效）
        
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GeoAssistant_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&GeoAssistant')

        # 初始化日志记录
        self.init_logging()

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        self.agent = Agent()

        self.agent.add_tool(list_project_layers)
        self.agent.add_tool(create_buffer)
        self.agent.add_tool(vector_overlay)
        self.agent.add_tool(fix_geometries)
        self.agent.add_tool(resample_raster)
        self.agent.add_tool(get_raster_info)
        self.agent.add_tool(highlight_features)

    # 添加初始化日志方法
    def init_logging(self):
        """初始化日志记录系统"""
        # 创建日志目录
        log_dir = os.path.join(self.plugin_dir, 'logs')
        os.makedirs(log_dir, exist_ok=True)
        
        # 创建日志文件名（按日期）
        log_date = datetime.datetime.now().strftime("%Y-%m-%d")
        log_file = os.path.join(log_dir, f"GeoAssistant_{log_date}.log")
        
        # 配置日志
        logging.basicConfig(
            filename=log_file,
            level=logging.INFO,
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            datefmt='%Y-%m-%d %H:%M:%S'
        )
        self.logger = logging.getLogger("GeoAssistant")
        self.logger.info("=" * 80)
        self.logger.info("GeoAssistant 插件启动")
        self.logger.info(f"日志文件: {log_file}")
        self.logger.info("=" * 80)

    # noinspection PyMethodMayBeStatic
    # 核心插件方法
    def tr(self, message):
        """获取翻译字符串"""
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GeoAssistant', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True, add_to_menu=True,
                   add_to_toolbar=True, status_tip=None, whats_this=None, parent=None):
        """添加工具栏图标"""
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """创建菜单项和工具栏图标"""

        icon_path =os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'GeoAssistant'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """卸载插件"""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&GeoAssistant'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """运行插件主对话框"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            # 将插件目录传递给对话框
            self.dlg = GeoAssistantDialog(plugin_dir=self.plugin_dir)

            # 获取Cancel按钮（取消按钮）
            cancel_button = self.dlg.button_box.button(QtWidgets.QDialogButtonBox.Cancel)
            if cancel_button:
                cancel_button.setText("取消") 
                cancel_button.clicked.disconnect()
                cancel_button.clicked.connect(self.handle_pause)  # 连接到这里

            # 获取Ok按钮（发送按钮）
            ok_button = self.dlg.button_box.button(QtWidgets.QDialogButtonBox.Ok)
            if ok_button:
                ok_button.setText("发送")    
                ok_button.clicked.disconnect()
                ok_button.clicked.connect(self.handle_query)

            # 移除默认连接
            self.dlg.button_box.accepted.disconnect()
            self.dlg.button_box.rejected.disconnect()

            # 确保初始状态正确
            self.dlg.update_buttons_state(False)
        self.dlg.show()

    # 查询处理方法
    def handle_pause(self):
        """处理暂停请求"""
        self.dlg.stop_processing()

    def handle_query(self):
        """处理用户查询"""
        query = self.dlg.query_input.toPlainText().strip()
        if not query:
            return

        # 记录当前会话ID，确保结果出现在发起查询的对话中
        query_chat_id = self.dlg.current_chat_id

        # 通过对话框设置处理状态
        self.dlg.set_processing_state(query_chat_id, True, query)
        
        # 自动创建新会话（如果当前没有会话）
        if query_chat_id == -1 or not self.dlg.chat_history:
            self.dlg.new_chat()
            # 新建会话后更新会话ID
            query_chat_id = self.dlg.current_chat_id
        else:
            # 确保当前会话标记为活跃
            self.dlg.active_chat_ids.add(query_chat_id)

        # 添加用户消息
        self.dlg.add_message_to_chat(query_chat_id, "user", query)

        # 添加"处理中..."消息（标记为可替换）
        self.dlg.add_message_to_chat(query_chat_id, "bot", "处理中...")

        # 清除输入框内的内容
        self.dlg.query_input.clear()

        # 创建并启动工作线程，传递查询的会话ID
        self.worker = self.QueryWorker(self.agent, query_chat_id, query)
        self.worker.finished.connect(self.handle_query_result)
        self.worker.start()

    def handle_query_result(self, chat_id, query, response):
        """处理查询结果并更新UI"""
        # 检查该对话是否仍在处理中（未被暂停）
        if not self.dlg.is_processing(chat_id):
            return

        # 替换最后一条消息（"处理中..."）为实际响应
        self.dlg.add_message_to_chat(chat_id, "bot", response, replace_last=True)

        # 如果这个会话是当前显示的会话，则刷新显示
        if chat_id == self.dlg.current_chat_id:
            self.dlg.render_chat()

        # 设置处理状态为"非处理中"
        self.dlg.set_processing_state(chat_id, False, "")

        # 如果这个会话是当前显示的会话，则更新按钮状态
        if chat_id == self.dlg.current_chat_id:
            # 重新启用输入框和按钮
            ok_button = self.dlg.button_box.button(QtWidgets.QDialogButtonBox.Ok)
            if ok_button:
                ok_button.setEnabled(True)
            self.dlg.query_input.setFocus()

        # 检查是否有新图层添加的通知
        if "新图层已添加到地图" in response:
            # 提取图层名称
            layer_name = re.search(r"新图层已添加到地图: (.+?)$", response)
            if layer_name:
                layer_name = layer_name.group(1)
                # 高亮显示新图层
                self.highlight_layer_in_qgis(layer_name)

        # 更新聊天状态显示
        QtCore.QTimer.singleShot(100, self.dlg.update_chat_status)

        # 更新历史记录显示 - 确保只更新当前会话的状态
        if chat_id == self.dlg.current_chat_id:
            # 更新历史记录显示
            self.dlg.history_list.item(self.dlg.current_chat_id).setText(
                f"会话 {self.dlg.current_chat_id + 1} (活跃)"
            )

    # 辅助方法
    def highlight_layer_in_qgis(self, layer_name: str):
        """在QGIS中高亮显示新添加的图层"""
        # 查找图层
        layers = QgsProject.instance().mapLayersByName(layer_name)
        if not layers:
            self.logger.warning(f"高亮显示失败：找不到图层 '{layer_name}'")
            return

        layer = layers[0]
        self.logger.info(f"高亮显示图层: {layer_name}")

        # 设置图层可见
        root = QgsProject.instance().layerTreeRoot()
        layer_node = root.findLayer(layer.id())
        
        if not layer_node:
            self.logger.error(f"图层节点未找到: {layer_name}")
            return
            
        layer_node.setItemVisibilityChecked(True)

        # 将图层移动到顶部 - 使用更可靠的API
        parent = layer_node.parent()
        if parent:
            try:
                # 获取当前索引
                current_index = parent.children().index(layer_node)
                
                # 如果不在顶部则移动到顶部
                if current_index > 0:
                    parent.moveChild(current_index, 0)
                    self.logger.info(f"已将图层 '{layer_name}' 移动到图层树顶部")
            except Exception as e:
                self.logger.error(f"移动图层失败: {str(e)}")

        # 缩放到图层范围
        if self.iface.mapCanvas():
            try:
                self.iface.mapCanvas().setExtent(layer.extent())
                self.iface.mapCanvas().refresh()
                self.logger.info(f"已缩放到图层范围: {layer_name}")
            except Exception as e:
                self.logger.error(f"缩放到图层失败: {str(e)}")

    # 工作线程类
    class QueryWorker(QThread):
        """后台查询工作线程"""
        finished = pyqtSignal(int, str, str)  # 信号: (chat_id, query, response)

        def __init__(self, agent, chat_id, query):
            super().__init__()
            self.agent = agent
            self.chat_id = chat_id
            self.query = query

        def run(self):
            try:
                # 使用异步执行方法
                self.agent.execute_async(self.query, self.on_result_received)
            except Exception as e:
                self.finished.emit(self.chat_id, self.query, f"线程错误: {str(e)}")

        def on_result_received(self, response):
            """接收异步执行结果"""
            self.finished.emit(self.chat_id, self.query, response)
            