# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoAssistantDialog
                                 A QGIS plugin
 AI-powered geospatial analysis assistant for QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-22
        git sha              : $Format:%H$
        copyright            : (C) 2025 by cug_cj
        email                : 3118345614@qq.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets, QtGui
from qgis.PyQt import QtCore
from qgis.PyQt.QtGui import QColor, QBrush
import logging

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'GeoAssistant_dialog_base.ui'))


class GeoAssistantDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None, plugin_dir=None):
        """初始化对话框界面和状态"""
        super().__init__(parent)
        self.setupUi(self)

        # 保存插件目录路径
        self.plugin_dir = plugin_dir

        # 初始化属性
        self.current_chat_id = -1
        self.current_chat = []
        self.chat_history = []
        self.active_chat_ids = set()
        self.sidebar_visible = True
        self.chat_counter = 1       # 初始会话计数器
        self.chat_names = []        # 存储会话名称

        # 添加对话状态字典
        self.chat_states = {}   # {chat_id: {"is_processing": bool, "current_query": str}}

        # 加载图标
        self.load_sidebar_icons()

        # 连接侧边栏切换按钮
        self.btn_toggle_sidebar.clicked.connect(self.toggle_sidebar)

        self.user_style = """
            margin: 4px 20px 4px 100px;
            padding: 8px;
            text-align: right;
            background: #e3f2fd;
            border-radius: 15px 15px 0 15px;
        """
        self.bot_style = """
            margin: 4px 100px 4px 20px;
            padding: 8px;
            text-align: left;
            background: #f5f5f5;
            border-radius: 15px 15px 15px 0;
        """
        # 连接信号
        self.btn_new_chat.clicked.connect(self.new_chat)
        self.history_list.itemClicked.connect(self.load_chat)

        # 右键菜单
        self.history_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.history_list.customContextMenuRequested.connect(self.show_context_menu)

        # 设置窗口标志，启用最小化和最大化按钮
        self.setWindowFlags(
            self.windowFlags() | 
            QtCore.Qt.WindowMinimizeButtonHint |
            QtCore.Qt.WindowMaximizeButtonHint |
            QtCore.Qt.WindowSystemMenuHint
        )

        # 初始化第一个对话的状态
        if len(self.chat_history) == 0:
            self.new_chat()

    # 界面控制方法
    def load_sidebar_icons(self):
        """加载侧边栏切换按钮的图标"""
        # 构建图标路径
        hide_icon_path = os.path.join(self.plugin_dir, 'image', 'sidebar_hide.png')
        show_icon_path = os.path.join(self.plugin_dir, 'image', 'sidebar_show.png')
        
        # 设置图标
        self.hide_icon = QtGui.QIcon(hide_icon_path)
        self.show_icon = QtGui.QIcon(show_icon_path)
        
        # 设置初始图标
        self.btn_toggle_sidebar.setIcon(self.hide_icon)
        self.btn_toggle_sidebar.setIconSize(QtCore.QSize(16, 16))
        self.btn_toggle_sidebar.setText("")  # 清除文本

    def toggle_sidebar(self):
        """切换侧边栏的显示状态"""
        self.sidebar_visible = not self.sidebar_visible

        if self.sidebar_visible:
            self.sidebar_frame.show()
            self.btn_toggle_sidebar.setIcon(self.hide_icon)
        else:
            self.sidebar_frame.hide()
            self.btn_toggle_sidebar.setIcon(self.show_icon)

   # 状态管理方法
    def set_processing_state(self, chat_id, is_processing, current_query=""):
        """设置对话的处理状态"""
        self.chat_states[chat_id] = {
            "is_processing": is_processing,
            "current_query": current_query
        }
        
        # 如果是当前对话，更新按钮状态
        if chat_id == self.current_chat_id:
            self.update_buttons_state(is_processing)
    
    def is_processing(self, chat_id):
        """检查对话是否正在处理"""
        state = self.chat_states.get(chat_id, {"is_processing": False})
        return state["is_processing"]

    def update_buttons_state(self, is_processing):
        """根据处理状态更新按钮状态"""
        # 始终启用输入框
        self.query_input.setEnabled(True)
        
        # 获取按钮
        ok_button = self.button_box.button(QtWidgets.QDialogButtonBox.Ok)
        cancel_button = self.button_box.button(QtWidgets.QDialogButtonBox.Cancel)
        
        # 更新发送按钮
        if ok_button:
            ok_button.setEnabled(not is_processing)
            ok_button.setText("发送")
        
        # 更新取消按钮
        if cancel_button:
            cancel_button.setEnabled(is_processing)
            cancel_button.setText("暂停" if is_processing else "取消")

    # 消息处理方法
    def add_message_to_chat(self, chat_id, sender, message, replace_last=False):
        """向指定会话添加消息"""
        if chat_id < 0 or chat_id >= len(self.chat_history):
            return
            
        chat = self.chat_history[chat_id]
        """添加消息到聊天区域，支持替换最后一条消息"""
        # 如果是替换最后一条消息
        if replace_last and chat:
            # 仅当最后一条消息是"处理中..."时才替换
            if chat[-1][1] == "处理中...":
                # 替换最后一条消息
                chat[-1] = (sender, message)
            else:
                # 添加新消息而不是替换
                chat.append((sender, message))
        else:
            # 添加新消息
            chat.append((sender, message))

        # 如果这个会话是当前显示的会话，则刷新显示
        if chat_id == self.current_chat_id:
            self.current_chat = chat
            self.render_chat()

    def render_chat(self):
        """渲染整个聊天区域"""
        # 清空显示
        self.chat_display.clear()

        # 生成所有消息的HTML
        html_buffer = []
        for sender, msg in self.current_chat:
            if sender == "user":
                style = self.user_style
                prefix = "👤"
            elif sender == "bot":
                style = self.bot_style
                prefix = "🤖"
            else:
                style = "color:red;"
                prefix = "Unknown"

            html_buffer.append(f'''
                <div style="{style}">
                    <strong>{prefix}:</strong><br/>
                    {msg.replace('\n', '<br/>')}
                </div>
            ''')

        # 一次性设置内容
        self.chat_display.append(''.join(html_buffer))

        # 自动滚动到底部
        self.chat_display.verticalScrollBar().setValue(
            self.chat_display.verticalScrollBar().maximum()
        )

    def update_processing_state(self, message):
        """更新处理状态"""
        # 查找最后一条消息并更新
        html = self.chat_display.toHtml()
        if "处理中..." in html:
            last_msg_index = html.rfind("处理中...")
            if last_msg_index != -1:
                new_html = html[:last_msg_index] + message + html[last_msg_index + len("处理中..."):]
                self.chat_display.setHtml(new_html)

    # 会话管理方法
    def new_chat(self):
        """创建新会话"""
        # 检查是否存在空对话
        empty_chat_found = False
        empty_chat_index = -1
        
        # 查找第一个空对话
        for idx, chat in enumerate(self.chat_history):
            if not chat:  # 检查对话是否为空
                empty_chat_found = True
                empty_chat_index = idx
                break
        
        if empty_chat_found:
            # 如果存在空对话，直接切换到它
            self.current_chat_id = empty_chat_index
            # 加载并渲染空对话
            self.load_chat_by_index(empty_chat_index)
            # 显式渲染空对话
            self.current_chat = self.chat_history[empty_chat_index]
            self.render_chat()
            # 确保UI状态更新
            self.update_chat_status()
            # 初始化状态
            self.set_processing_state(empty_chat_index, False)
            return
        
        # 没有找到空对话，创建新会话
        new_id = len(self.chat_history)

        # 使用计数器生成唯一名称
        chat_name = f"会话 {self.chat_counter}"
        self.chat_counter += 1  # 递增计数器

        self.chat_history.append([])
        self.current_chat_id = new_id
        self.active_chat_ids.add(new_id)

        # 添加列表项并更新状态
        item = QtWidgets.QListWidgetItem(chat_name)
        self.history_list.addItem(item)
        
        # 确保名称存储正确
        if new_id >= len(self.chat_names):
            self.chat_names.append(chat_name)
        else:
            self.chat_names.insert(new_id, chat_name)

        # 清空当前显示
        self.current_chat = self.chat_history[new_id]
        self.chat_display.clear()
        self.query_input.setFocus()

        # 修改列表项显示 - 添加🚀标志
        item = self.history_list.item(new_id)
        item.setText(f"{chat_name} 🚀")
        
        # 确保UI状态更新
        self.update_chat_status()
        # 显式渲染空对话
        self.render_chat()

        # 初始化新对话状态为"非处理中"
        self.set_processing_state(new_id, False)
        # 更新按钮状态
        self.update_buttons_state(False)

    def load_chat_by_index(self, index: int):
        """根据索引加载对话"""
        if 0 <= index < self.history_list.count():
            item = self.history_list.item(index)
            self.load_chat(item)
            # 显式渲染对话内容
            self.render_chat()

    def load_chat(self, item):
        """加载历史对话"""
        index = self.history_list.row(item)
        if 0 <= index < len(self.chat_history):
            # 防止重复加载
            if index == self.current_chat_id:
                return

            # 暂时禁用UI更新
            self.chat_display.setUpdatesEnabled(False)

            try:
                # 更新活跃状态
                prev_active = self.current_chat_id
                self.current_chat_id = index
                self.active_chat_ids.add(index)

                # 设置当前聊天记录
                self.current_chat = self.chat_history[index]

                # 批量生成HTML内容
                html_buffer = []
                for sender, msg in self.chat_history[index]:
                    if sender == "user":
                        style = self.user_style
                        prefix = "👤"
                    elif sender == "bot":
                        style = self.bot_style
                        prefix = "🤖"
                    else:
                        style = "color:red;"
                        prefix = "Unknown"

                    html_buffer.append(f'''
                        <div style="{style}">
                            <strong>{prefix}:</strong><br/>
                            {msg.replace('\n', '<br/>')}
                        </div>
                    ''')

                # 一次性设置内容
                self.chat_display.clear()
                self.chat_display.append(''.join(html_buffer))

                # 自动滚动到底部
                self.chat_display.verticalScrollBar().setValue(
                    self.chat_display.verticalScrollBar().maximum()
                )

                # 刷新状态显示
                if prev_active != -1:
                    self.update_chat_status()

                # 更新按钮状态为当前对话状态
                state = self.chat_states.get(index, {"is_processing": False})
                self.update_buttons_state(state["is_processing"])

            finally:
                # 恢复UI更新
                self.chat_display.setUpdatesEnabled(True)

            self.query_input.setFocus()

    def update_chat_status(self):
        """更新会话状态显示"""
        for i in range(self.history_list.count()):
            item = self.history_list.item(i)
            # 使用存储的名称
            if i < len(self.chat_names):
                name = self.chat_names[i]
            else:
                # 如果名称列表不完整，使用默认名称
                name = f"会话 {i + 1}"

            is_active = i == self.current_chat_id
            item.setText(f"{name} {'🚀' if is_active else ''}")
            item.setBackground(QColor("#e3f2fd") if is_active else QBrush())

    # 右键菜单方法
    def show_context_menu(self, pos):
        """显示会话右键菜单"""
        menu = QtWidgets.QMenu()
        rename_action = menu.addAction("重命名")
        delete_action = menu.addAction("删除")

        item = self.history_list.itemAt(pos)
        if not item:
            return

        # 连接信号
        rename_action.triggered.connect(lambda: self.rename_chat(item))
        delete_action.triggered.connect(lambda: self.delete_chat(item))

        menu.exec_(self.history_list.mapToGlobal(pos))

    def rename_chat(self, item):
        """重命名会话"""
        index = self.history_list.row(item)
        new_name, ok = QtWidgets.QInputDialog.getText(
            self,
            '重命名会话',
            '输入新名称:',
            text=self.chat_names[index] if index < len(self.chat_names) else f"会话 {index + 1}"
        )

        if ok and new_name:
            # 更新名称存储
            if index >= len(self.chat_names):
                self.chat_names += [f"会话 {i + 1}" for i in range(len(self.chat_names), index + 1)]
            self.chat_names[index] = new_name

            # 更新显示
            item.setText(f"{new_name} {'🚀' if index == self.current_chat_id else ''}")

    def delete_chat(self, item):
        """删除会话"""
        index = self.history_list.row(item)
        reply = QtWidgets.QMessageBox.question(
            self,
            '确认删除',
            '确定要删除这个会话吗？',
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No
        )

        if reply == QtWidgets.QMessageBox.Yes:
            # 记录是否是当前对话
            is_current = (index == self.current_chat_id)
            
            # 删除数据
            del self.chat_history[index]
            if index < len(self.chat_names):
                del self.chat_names[index]

            # 更新列表显示
            self.history_list.takeItem(index)

            # 更新后续会话编号
            for i in range(index, self.history_list.count()):
                item = self.history_list.item(i)
                if i < len(self.chat_names):
                    name = self.chat_names[i]
                else:
                    name = f"会话 {i + 1}"
                item.setText(f"{name} {'🚀' if i == self.current_chat_id else ''}")

            # 处理当前对话
            if is_current:
                if self.history_list.count() > 0:  # 如果有其他会话
                    # 确保加载新对话并刷新UI
                    self.current_chat_id = 0  # 设置为第一个对话
                    self.current_chat = self.chat_history[0]  # 直接设置当前聊天内容
                    self.render_chat()  # 强制刷新聊天显示
                    # 更新列表项状态
                    self.update_chat_status()
                else:  # 没有其他会话
                    self.new_chat()
            else:
                # 如果不是当前对话，调整current_chat_id
                if index < self.current_chat_id:
                    self.current_chat_id -= 1

            # 确保UI刷新
            self.update_chat_status()

    # 处理控制方法
    def stop_processing(self):
        """停止当前对话的处理"""
        if self.current_chat_id not in self.chat_states:
            return
            
        state = self.chat_states[self.current_chat_id]
        if state["is_processing"]:
            # 更新状态
            state["is_processing"] = False
            state["current_query"] = ""
            
            # 更新消息
            if self.current_chat and self.current_chat[-1][1] == "处理中...":
                self.current_chat[-1] = ("bot", "用户已取消对话")
                self.render_chat()
            
            # 更新按钮状态
            self.update_buttons_state(False)
